server:
  origin: https://httpbin.org/
  # port: 1323
  secret: pls_delete_cache_maboy
  timeout: 10 # in seconds
  ratelimit:
    rate: 20
    duration: 60

redis:
  port: 6379
  addr: redis
  password:
  db: 5
  TTL: 5 # in minutes

blacklist:
  - /uuid
  - /delay/(.+)

logger:
  level: DEBUG # INFO, DEBUG, ERROR
  file: app.log # File name or blank line for stdout
