server:
  origin: https://httpbin.org/
  # port: 1323
  secret: pls_delete_cache_maboy

redis:
  port: 6379
  addr: localhost
  password:
  db: 5
  TTL: 5 # in minutes

blacklist:
  - /uuid
  - /delay/(.+)
  
logger:
  level: DEBUG # now support only INFO and DEBUG
  file: app.log